Somativa/Models/Compra.cs
using System.ComponentModel;

namespace Somativa.Models
{
    public class Compra
    {
        public Guid CompraId { get; set; }
        [DisplayName("Nota Fiscal")]
        public int Nota { get; set; }
        [DisplayName("Data e hora")]
        public DateTime DataHora { get; set; }
        public IEnumerable<CompraItem>? CompraItems { get; set; }
    }
}

Somativa/Controllers/CompraItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Somativa.Data;
using Somativa.Models;

namespace Somativa.Controllers
{
	[Authorize(Roles = "Admin,Operador")]
	public class CompraItemsController : Controller
    {
        private readonly SprintContext _context;

        public CompraItemsController(SprintContext context)
        {
            _context = context;
        }

        // GET: CompraItems
        public async Task<IActionResult> Index(Guid Id)
        {
            var sprintContext = _context.CompraItens.Include(c => c.Compra).Include(c => c.Produto);
            ViewData["CompraId"] = Id;
            return View(await sprintContext.Where(i => i.CompraId == Id).ToListAsync());
        }

        // GET: CompraItems/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.CompraItens == null)
            {
                return NotFound();
            }

            var compraItem = await _context.CompraItens
                .Include(c => c.Compra)
                .Include(c => c.Produto)
                .FirstOrDefaultAsync(m => m.CompraItemId == id);
            if (compraItem == null)
            {
                return NotFound();
            }

            return View(compraItem);
        }

        // GET: CompraItems/Create
        public IActionResult Create(Guid Id)
        {
            //ViewData["CompraId"] = new SelectList(_context.Compras, "CompraId", "CompraId");            
            ViewData["ProdutoId"] = new SelectList(_context.Produtos, "ProdutoId", "Nome");
            ViewData["CompraId"] = Id;
            return View();
        }

        // POST: CompraItems/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CompraItemId,CompraId,ProdutoId,Quantidade,Unitario")] CompraItem compraItem)
        {
            if (ModelState.IsValid)
            {
                compraItem.CompraItemId = Guid.NewGuid();
                _context.Add(compraItem);
                await _context.SaveChangesAsync();

                Produto p = _context.Produtos.Where(p => p.ProdutoId == compraItem.ProdutoId).FirstOrDefault();
                p.Estoque += compraItem.Quantidade;
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index), new { Id = compraItem.CompraId });
            }
            ViewData["CompraId"] = new SelectList(_context.Compras, "CompraId", "Nota", compraItem.CompraId);
            ViewData["ProdutoId"] = new SelectList(_context.Produtos, "ProdutoId", "Nome", compraItem.ProdutoId);
            return View(compraItem);
        }

        // GET: CompraItems/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.CompraItens == null)
            {
                return NotFound();
            }

            var compraItem = await _context.CompraItens.FindAsync(id);
            if (compraItem == null)
            {
                return NotFound();
            }
            ViewData["CompraId"] = new SelectList(_context.Compras, "CompraId", "Nota", compraItem.CompraId);
            ViewData["ProdutoId"] = new SelectList(_context.Produtos, "ProdutoId", "Nome", compraItem.ProdutoId);
            return View(compraItem);
        }

        // POST: CompraItems/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("CompraItemId,CompraId,ProdutoId,Quantidade,Unitario")] CompraItem compraItem)
        {
            if (id != compraItem.CompraItemId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(compraItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompraItemExists(compraItem.CompraItemId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CompraId"] = new SelectList(_context.Compras, "CompraId", "Nota", compraItem.CompraId);
            ViewData["ProdutoId"] = new SelectList(_context.Produtos, "ProdutoId", "Nome", compraItem.ProdutoId);
            return View(compraItem);
        }

        // GET: CompraItems/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.CompraItens == null)
            {
                return NotFound();
            }

            var compraItem = await _context.CompraItens
                .Include(c => c.Compra)
                .Include(c => c.Produto)
                .FirstOrDefaultAsync(m => m.CompraItemId == id);
            if (compraItem == null)
            {
                return NotFound();
            }

            return View(compraItem);
        }

        // POST: CompraItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_context.CompraItens == null)
            {
                return Problem("Entity set 'SprintContext.CompraItens'  is null.");
            }
            var compraItem = await _context.CompraItens.FindAsync(id);
            if (compraItem != null)
            {
                _context.CompraItens.Remove(compraItem);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CompraItemExists(Guid id)
        {
          return (_context.CompraItens?.Any(e => e.CompraItemId == id)).GetValueOrDefault();
        }
    }
}

Somativa/Controllers/ComprasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Somativa.Data;
using Somativa.Models;

namespace Somativa.Controllers
{
	[Authorize(Roles = "Admin,Operador")]
	public class ComprasController : Controller
    {
        private readonly SprintContext _context;

        public ComprasController(SprintContext context)
        {
            _context = context;
        }

        // GET: Compras
        public async Task<IActionResult> Index()
        {
              return _context.Compras != null ? 
                          View(await _context.Compras.ToListAsync()) :
                          Problem("Entity set 'SprintContext.Compras'  is null.");
        }

        // GET: Compras/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.Compras == null)
            {
                return NotFound();
            }

            var compra = await _context.Compras
                .FirstOrDefaultAsync(m => m.CompraId == id);
            if (compra == null)
            {
                return NotFound();
            }

            return View(compra);
        }

        // GET: Compras/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Compras/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CompraId,Nota,DataHora")] Compra compra)
        {
            if (ModelState.IsValid)
            {
                compra.CompraId = Guid.NewGuid();
                _context.Add(compra);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(compra);
        }

        // GET: Compras/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.Compras == null)
            {
                return NotFound();
            }

            var compra = await _context.Compras.FindAsync(id);
            if (compra == null)
            {
                return NotFound();
            }
            return View(compra);
        }

        // POST: Compras/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("CompraId,Nota,DataHora")] Compra compra)
        {
            if (id != compra.CompraId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(compra);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompraExists(compra.CompraId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(compra);
        }

        // GET: Compras/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.Compras == null)
            {
                return NotFound();
            }

            var compra = await _context.Compras
                .FirstOrDefaultAsync(m => m.CompraId == id);
            if (compra == null)
            {
                return NotFound();
            }

            return View(compra);
        }

        // POST: Compras/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_context.Compras == null)
            {
                return Problem("Entity set 'SprintContext.Compras'  is null.");
            }
            var compra = await _context.Compras.FindAsync(id);
            if (compra != null)
            {
                _context.Compras.Remove(compra);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CompraExists(Guid id)
        {
          return (_context.Compras?.Any(e => e.CompraId == id)).GetValueOrDefault();
        }
    }
}

Somativa/Views/Compras/Create.cshtml
@model Somativa.Models.Compra

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Compra</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nota" class="control-label"></label>
                <input asp-for="Nota" class="form-control" />
                <span asp-validation-for="Nota" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataHora" class="control-label"></label>
                <input asp-for="DataHora" class="form-control" />
                <span asp-validation-for="DataHora" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn" style="background-color:lightseagreen" />
            </div>
        </form>
    </div>
</div>
<br />
<div>
    <a asp-action="Index" class="btn m- 1 text-white" style="background-color:darkslategrey">
        <svg bootstrap-icon="XCircle" width="16" height="16" aria-label="Cancelar"></svg>
        Cancelar 
    </a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Somativa/Views/Compras/Delete.cshtml
@model Somativa.Models.Compra

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Você tem certaza que quer apagar?</h3>
<div>
    <h4>Compra</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nota)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nota)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataHora)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataHora)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CompraId" />

        <button type="submit" class="btn m-2 text-white" style="background-color:darkslategrey">
            <svg bootstrap-icon="Trash2" width="16" height="16" aria-label="Delete"></svg> Deletar
        </button>

        <a asp-action="Index" class="btn m- 1 text-white" style="background-color:darkslategrey">
            <svg bootstrap-icon="XCircle" width="16" height="16" aria-label="Cancelar"></svg>
            Cancelar
        </a>
    </form>
</div>

Somativa/Views/Compras/Details.cshtml
@model Somativa.Models.Compra

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Compra</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nota)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nota)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataHora)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataHora)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" class="btn m-2 text-white" style="background-color:lightseagreen" asp-route-id="@Model.CompraId">
        <svg bootstrap-icon="Pencil" width="16" height="16" aria-label="Editar"></svg>
        Editar
    </a>

    <a asp-action="Index" class="btn m-1 text-white" style="background-color:darkslategrey">
        <svg bootstrap-icon="XCircle" width="16" height="16" aria-label="Cancelar"></svg>
        Cancelar
    </a>
</div>

Somativa/Views/Compras/Edit.cshtml
@model Somativa.Models.Compra

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Compra</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CompraId" />
            <div class="form-group">
                <label asp-for="Nota" class="control-label"></label>
                <input asp-for="Nota" class="form-control" />
                <span asp-validation-for="Nota" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataHora" class="control-label"></label>
                <input asp-for="DataHora" class="form-control" />
                <span asp-validation-for="DataHora" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Save" class="btn text-white" style="background-color:cadetblue" />
            </div>
        </form>
    </div>
</div>
<br />
<div>
    <a asp-action="Index" class="btn m- 1 text-white" style="background-color:darkslategrey">
        <svg bootstrap-icon="XCircle" width="16" height="16" aria-label="Cancelar"></svg>
        Cancelar
    </a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Somativa/Views/Compras/Index.cshtml
@model IEnumerable<Somativa.Models.Compra>

@{
    ViewData["Title"] = "Index";
}

<h1>Compras</h1>

<p>
    <a asp-action="Create" class="btn btn-warning m-2">
        <svg bootstrap-icon="Plus" width="16" height="16" aria-label="Create"></svg>
        Criar
    </a>
</p>

<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nota)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataHora)
            </th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nota)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataHora)
            </td>
                <td class="text-end">
                    <a asp-action="Edit" class="btn m-2 text-white" style="background-color:lightseagreen" asp-route-id="@item.CompraId">
                        <svg bootstrap-icon="Pencil" width="16" height="16" aria-label="Editar"></svg>
                        Editar
                    </a>
                    <a asp-action="Details" class="btn m-2 text-white" style="background-color:cadetblue" asp-route-id="@item.CompraId">
                        <svg bootstrap-icon="InfoCircle" width="16" height="16" aria-label="Mais"></svg>
                        Detalhar
                    </a>
                    <a asp-action="Delete" class="btn m-2 text-white" style="background-color:darkslategrey" asp-route-id="@item.CompraId">
                        <svg bootstrap-icon="Trash2" width="16" height="16" aria-label="Deletar"></svg>
                        Deletar
                    </a>
                    <a asp-controller="CompraItems" asp-action="Index" class="btn m-2 text-white" style="background-color:lightblue" asp-route-id="@item.CompraId">
                        <svg bootstrap-icon="Trash2" width="16" height="16" aria-label="Items"></svg>
                        Itens
                    </a>
            </td>
        </tr>
}
    </tbody>
</table>