Somativa/Controllers/RelatorioController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NuGet.Common;
using Somativa.Data;
using Somativa.Models;
using System.Security.Policy;

namespace Somativa.Controllers
{
    [Authorize(Roles = "Admin,Gerente")]
    public class RelatorioController : Controller
    {
        private readonly SprintContext _context;

        public RelatorioController(SprintContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> RelatProd()
        {
            var prod = await _context.Produtos.Include(c => c.Categoria).ToListAsync();
            ViewData["Categ"] = await _context.Categorias.ToListAsync();
            
            return View(prod);
        }

        public async Task<IActionResult> SearchProd(Guid inCategoria, string inNome)
        {
			var prod = await _context.Produtos.Include(c => c.Categoria).ToListAsync();

            if (inNome != null) 
            {
				inNome = inNome.Trim().ToUpper();
                prod = prod.Where(i => i.Nome.ToUpper().Contains(inNome)).ToList();
			}

            if (!inCategoria.ToString().Equals("00000000-0000-0000-0000-000000000000"))
            {
                prod = prod.Where(i => i.CategoriaId == inCategoria).ToList();
            }

			ViewData["Categ"] = await _context.Categorias.ToListAsync();
			return View("RelatProd", prod);
        }

		public async Task<IActionResult> RelatMov()
        {
            var mov = await MovimentacaoList.getList(_context);
            ViewData["Produtos"] =  await _context.Produtos.ToListAsync();

			return View(mov);
        }

        public async Task<IActionResult> SearchMov(DateTime? inDataIni, DateTime? inDataFim, int inTipo, string inProduto)
        {
			var mov = await MovimentacaoList.getList(_context);
			ViewData["Produtos"] = await _context.Produtos.ToListAsync();

            if (inDataIni != null) mov = mov.Where(i => i.DataHora >= inDataIni).ToList();
			if (inDataFim != null) mov = mov.Where(i => i.DataHora <= inDataFim).ToList();

            if (inTipo == 1) mov = mov.Where(i => i.TipoMovimentacao.Equals("Entrada")).ToList();
			if (inTipo == 2) mov = mov.Where(i => i.TipoMovimentacao.Equals("Saída")).ToList();

            if (!inProduto.ToString().Equals("Todos"))
                mov = mov.Where(i => i.Produto.Equals(inProduto)).ToList();

			return View("RelatMov", mov);
        }

        public IActionResult GetImage2(string fileName) 
        {
           
            var imgPath = Path.Combine("../MinhasImagens", fileName );
			if (System.IO.File.Exists(imgPath))
            {
				var imageBytes = System.IO.File.ReadAllBytes(imgPath);
				return File(imageBytes, "image/png");
			}
			return NotFound();
		}

		public IActionResult GetImage(string imageName)
		{
			string applicationPath = AppDomain.CurrentDomain.BaseDirectory;
            string teste = System.IO.Directory.GetCurrentDirectory();
			//var imagePath = Path.Combine(applicationPath + "Somativa\\MinhasImagens", imageName);
		
			var imagePath = teste + "\\minhasimagens\\imagem.png";

			if (System.IO.File.Exists(imagePath))
			{
				var imageBytes = System.IO.File.ReadAllBytes(imagePath);
				return File(imageBytes, "image/png");
			}

			return NotFound();
		}



	}
}

Somativa/Views/Relatorio/RelatMov.cshtml
@model IEnumerable<Somativa.Models.Movimentacao>

@{
	ViewData["Title"] = "RelatMov";
	var prod = ViewData["Produtos"] as List<Produto>;
	prod.Insert(0, new Produto { ProdutoId = new Guid(), Nome = "Todos" });
}

<h1>Relatório de Movimentação</h1>

<form>
	<div class="mt-3 mb-3">
		<label>Data início</label>
		<input name="inDataIni" type="date" class="ms-3 me-3" />
		<label>Data fim</label>
		<input name="inDataFim" type="date" class="ms-3 me-3" />
		<label>Tipo de movimentação</label>
		<select name="inTipo" class="ms-3 me-3">
			<option value="0">Todos</option>
			<option value="1">Entradas</option>
			<option value="2">Saídas</option>
		</select>
		<label>Produto</label>
		<select name="inProduto" class="ms-3 me-3">
			@foreach (var item in prod)
			{
				<option value="@item.Nome">@item.Nome</option>
			}
		</select>
		<button asp-action="SearchMov" class="btn btn-success">Filtrar</button>
	</div>
</form>


<table class="table">
	<thead>
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.Nota)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.DataHora)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.TipoMovimentacao)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Produto)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Quantidade)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Unitario)
			</th>

		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.Nota)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.DataHora)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.TipoMovimentacao)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Produto)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Quantidade)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Unitario)
				</td>

			</tr>
		}
	</tbody>
</table>

Somativa/Views/Relatorio/RelatProd.cshtml
@model IEnumerable<Somativa.Models.Produto>

@{
	ViewData["Title"] = "RelatProd";

	List<Categoria> categorias = new List<Categoria>();
	categorias.Add(new Categoria { CategoriaId=new Guid(), Nome="Todas" });
	var categ = ViewData["Categ"] as List<Categoria>;

	foreach (var item in categ)
	{
		categorias.Add(new Categoria { CategoriaId = item.CategoriaId, Nome = item.Nome });
	}
}

<h1>Relatório de Produção</h1>

<!--
<img src="@Url.Action("GetImage", "Relatorio", new { imageName = "imagem.png" })" alt="Descrição da imagem">
-->
<form>
	<div id="filtros">
		<label>Categoria</label>
		<select name="inCategoria" class="ms-3 me-3">
			@foreach (var item in categorias)
			{
				<option value="@item.CategoriaId">@item.Nome</option>
			}
			
		</select>
		<label>Nome</label>
		<input name="inNome" type="text" class="ms-3 me-3" />
		<button asp-action="SearchProd" class="btn btn-success">Filtrar</button>
	</div>
</form>

<table class="table">
	<thead>
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.Nome)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Categoria.Nome)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Estoque)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Preco)
			</th>

		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.Nome)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Categoria.Nome)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Estoque)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Preco)
				</td>

			</tr>
		}
	</tbody>
</table>